package com.edison.blackboard.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.UUID;

@DynamoDBTable(tableName = "announcement")
@DynamoDBDocument
public class Announcement {
    private UUID id;
    private String announcementText = "";
    private Board board;
    private UUID boardId;

    public Announcement(Announcement announcement) {
        setId(announcement.getId());
        setBoard(announcement.getBoard());
        setAnnouncementText(announcement.getAnnouncementText());
        setBoardId(announcement.getBoardId());
    }

    public Announcement() {

    }

    public Announcement(Announcement announcement, boolean light) {
        if(light) {
            setBoardId(announcement.getBoardId());
            setId(announcement.getId());
            setAnnouncementText(announcement.getAnnouncementText());
        }
    }

    @DynamoDBHashKey(attributeName = "announcementid")
    @DynamoDBAutoGeneratedKey
    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getAnnouncementText() {
        return announcementText;
    }

    public void setAnnouncementText(String announcementText) {
        this.announcementText = announcementText;
    }

    @DynamoDBAttribute
    public UUID getBoardId() {
        return this.boardId;
    }

    public void setBoardId(UUID boardId) {
        this.boardId = boardId;
    }

    @DynamoDBAttribute
    public Board getBoard() {
        return this.board;
    }

    public Announcement setBoard(Board board) {
        Board newBoard = new Board(board, true);
        setBoardId(newBoard.getId());
        this.board = newBoard;
        return this;
    }
}
