package com.edison.blackboard.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.UUID;

@DynamoDBTable(tableName = "announcement")
@DynamoDBDocument
public class Announcement {
    private UUID id;
    private String announcementText;
    private Board board;
    private UUID boardId;

    public Announcement(Announcement announcement) {
        setId(announcement.getId());
        setBoard(announcement.getBoard());
        setAnnouncementText(announcement.getAnnouncementText());
    }

    public Announcement(Board board) {
        setBoard(board);
    }

    public Announcement() {}

    @DynamoDBHashKey(attributeName = "announcementid")
    @DynamoDBAutoGeneratedKey
    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getAnnouncementText() {
        return announcementText;
    }

    public void setAnnouncementText(String announcementText) {
        this.announcementText = announcementText;
    }

    @DynamoDBAttribute
    public UUID getBoardId() {
        return this.boardId;
    }

    public void setBoardId(UUID boardId) {
        this.boardId = boardId;
    }

    @DynamoDBAttribute
    public Board getBoard() {
        return this.board;
    }

    public void setBoard(Board board) {
        setBoardId(board.getId());
        this.board = board;
    }
}
