package com.edison.blackboard.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.UUID;

@DynamoDBTable(tableName = "board")
@DynamoDBDocument
public class Board {
    private UUID id;
    private Course course;
    private UUID courseId;

    public Board(Board board) {
        setId(board.getId());
        setCourseId(board.getCourseId());
        setId(board.getId());
    }

    public Board(Board board, boolean light) {
        if(light) {
            setCourse(board.getCourse());
            setId(board.getId());
        }
    }

    public Board() {}

    public Board(Course course) {
        setCourse(course);
    }

    @DynamoDBHashKey(attributeName = "boardid")
    @DynamoDBAutoGeneratedKey
    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public UUID getCourseId() {
        return courseId;
    }

    public void setCourseId(UUID courseId) {
        this.courseId = courseId;
    }

    @DynamoDBAttribute
    public Course getCourse() {
        return this.course;
    }

    public void setCourse(Course course) {
        setCourseId(this.course.getCourseId());
        this.course = course;
    }
}
