package com.edison.blackboard.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.UUID;

@DynamoDBTable(tableName = "board")
@DynamoDBDocument
public class Board {
    private UUID id;
    private String boardId;
    private UUID courseId;

    public Board(Board board) {
        setBoardId(board.getBoardId());
        setCourseId(board.getCourseId());
        setId(board.getId());
    }

    public Board(Board board, boolean light) {
        if(light) {
            setCourseId(board.getCourseId());
            setBoardId(board.getBoardId());
        }
    }

    @DynamoDBHashKey(attributeName = "boardid")
    @DynamoDBAutoGeneratedKey
    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getBoardId() {
        return boardId;
    }

    public void setBoardId(String boardId) {
        this.boardId = boardId;
    }

    @DynamoDBAttribute
    public UUID getCourseId() {
        return courseId;
    }

    public void setCourseId(UUID courseId) {
        this.courseId = courseId;
    }
}
