package com.edison.blackboard.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "course")
@DynamoDBDocument
public class Course implements Serializable {
    private String name;
    private UUID id;
    private List<Student> studentList = new ArrayList<>();
    private Professor professor;
    private Student ta;

    public Course(Course course) {
        setName(course.getName());
        setId(course.getId());
        setStudentList(course.getStudentList());
        setTa(course.getTa());
        setProfessor(course.getProfessor());
    }

    public Course() {
    }

    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBHashKey(attributeName = "courseid")
    @DynamoDBAutoGeneratedKey
    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public List<Student> getStudentList() {
        return studentList;
    }

    public void setStudentList(List<Student> studentList) {
        this.studentList = studentList;
    }

    @DynamoDBAttribute
    public Professor getProfessor() {
        return professor;
    }

    public void setProfessor(Professor professor) {
        this.professor = professor;
    }

    @DynamoDBAttribute
    public Student getTa() {
        return ta;
    }

    public void setTa(Student ta) {
        this.ta = ta;
    }

    public Course addStudent(Student student) {
        this.studentList.add(student);
        return this;
    }

    public Course removeStudent(Student student) {
        for(int i = 0; i < studentList.size(); i++) {
            if(studentList.get(i).getId().equals(student.getId())) {
                studentList.remove(i);
                return this;
            }
        }
        return null;
    }

}
