package com.edison.blackboard.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.io.Serializable;
import java.util.List;
import java.util.UUID;

@DynamoDBTable(tableName = "professor")
public class Professor implements Serializable {
    private static final long serialVersionUID = 1L;
    private UUID id;
    private String name;
    private String program;
    private List<Course> courseList;

    public Professor(Professor professor) {
        setId(professor.getId());
        setName(professor.getName());
        setProgram(professor.getProgram());
        setCourseList(professor.courseList);
    }

    public Professor() {}

    @DynamoDBHashKey(attributeName = "professorid")
    @DynamoDBAutoGeneratedKey
    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute
    public String getProgram() {
        return program;
    }

    public void setProgram(String program) {
        this.program = program;
    }

    @DynamoDBAttribute
    public List<Course> getCourseList() {
        return courseList;
    }

    public void setCourseList(List<Course> courseList) {
        this.courseList = courseList;
    }
}
