package com.edison.blackboard.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.UUID;

@DynamoDBTable(tableName = "student")
@DynamoDBDocument
public class Student implements Serializable {
    private static final long serialVersionUID = 1L;
    private UUID id;
    private String name = "";
    private String program = "";
    private List<Course> courseList = new ArrayList<>();
    private String studentId;

    private String lastName = "";
    private String firstName = "";
    private Date joiningDate;

    public Student(Student student) {
        setId(student.getId());
        setName(student.getName());
        setProgram(student.getProgram());
        setCourseList(student.getCourseList());
        setJoiningDate(student.getJoiningDate());
    }

    public Student(Student student, boolean light) {
        if(light) {
            setId(student.getId());
            setName(student.getName());
            setProgram(student.getProgram());
        }
    }

    public Student() {
        setJoiningDate(new Date());
    }

    @DynamoDBHashKey(attributeName = "studentid")
    @DynamoDBAutoGeneratedKey
    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute
    public String getProgram() {
        return program;
    }

    public Student setProgram(String program) {
        this.program = program;
        return this;
    }

    public Student removeProgram(Program program) {
        if(this.getProgram().equals(program.getName())) setProgram("");
        else System.out.println("Program Not Found");
        return this;
    }

    @DynamoDBAttribute
    public String getStudentId() {
        return studentId;
    }

    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    @DynamoDBAttribute
    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @DynamoDBAttribute
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @DynamoDBAttribute
    public Date getJoiningDate() {
        return joiningDate;
    }

    public void setJoiningDate(Date joiningDate) {
        this.joiningDate = joiningDate;
    }

    @DynamoDBAttribute
    public List<Course> getCourseList() {
        return courseList;
    }

    public void setCourseList(List<Course> courseList) {
        this.courseList = courseList;
    }

    public Student addCourse(Course course) {
        this.courseList.add(new Course(course, true));
        return this;
    }

    public Student removeCourse(Course course) {
        for(int i = 0; i < courseList.size(); i++)
            if(courseList.get(i).getId().equals(course.getId())) {
                courseList.remove(i);
                return this;
            }
        return null;
    }
}
