package com.edison.blackboard.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

@DynamoDBTable(tableName = "student")
@DynamoDBDocument
public class Student implements Serializable {
    private static final long serialVersionUID = 1L;
    private UUID id;
    private String name;
    private String program;
    private List<Course> courseList = new ArrayList<>();

    public Student(Student student) {
        setId(student.getId());
        setName(student.getName());
        setProgram(student.getProgram());
        setCourseList(student.getCourseList());
    }

    public Student() {}

    @DynamoDBHashKey(attributeName = "studentid")
    @DynamoDBAutoGeneratedKey
    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute
    public String getProgram() {
        return program;
    }

    public void setProgram(String program) {
        this.program = program;
    }

    @DynamoDBAttribute
    public List<Course> getCourseList() {
        return courseList;
    }

    public void setCourseList(List<Course> courseList) {
        this.courseList = courseList;
    }

    public Student addCourse(Course course) {
        this.courseList.add(course);
        return this;
    }
}
